// action types of APP
export const INIT_DASHBOARD = "INIT_DASHBOARD";
export const INIT_DASHBOARD_SUCCESS = "INIT_DASHBOARD_SUCCESS";
export const INIT_TASK = "INIT_TASK";
export const INIT_TASK_SUCCESS = "INIT_TASK_SUCCESS";
export const INIT_LIST = "INIT_LIST";
export const INIT_LIST_SUCCESS = "INIT_LIST_SUCCESS";
export const INIT_TAG = "INIT_TAG";
export const INIT_TAG_SUCCESS = "INIT_TAG_SUCCESS";
export const INIT_SCHEDULE = "INIT_SCHEDULE";
export const INIT_SCHEDULE_SUCCESS = "INIT_SCHEDULE_SUCCESS";
export const INIT_FAILED = "INIT_FAILED";
export const SET_SELECTED_TASK = "SET_SELECTED_TASK";
export const ON_ADDING_TASK = "ON_ADDING_TASK";
export const ON_EDITING_TASK = "ON_EDITING_TASK";

// action types for UIBEHAVIOR
export const INIT_SIDEBAR = "INIT_SIDEBAR";
export const INIT_SIDEBAR_LIST = "INIT_SIDEBAR_LIST";
export const INIT_SIDEBAR_TAG = "INIT_SIDEBAR_TAG";
export const INIT_SIDEBAR_SCHEDULE = "INIT_SIDEBAR_SCHEDULE";
export const SET_SIDEBAR_MENU_ITEM = "SET_SIDEBAR_MENU_ITEM";
export const SET_SIDEBAR_LIST_PICKER = "SET_SIDEBAR_LIST_PICKER";
export const SET_SIDEBAR_LIST_ITEM = "SET_SIDEBAR_LIST_ITEM";
export const SET_DETAILS_VIEW_TASK = "SET_DETAILS_VIEW_TASK";
export const SET_DETAILS_ADD_TASK = "SET_DETAILS_ADD_TASK";
export const SET_DETAILS_EDIT_TASK = "SET_DETAILS_EDIT_TASK";
export const SET_MAKE_NEW_TASK = "SET_MAKE_NEW_TASK";
export const SET_MAKE_ROUTINE = "SET_MAKE_ROUTINE";
export const SET_MODAL = "SET_MODAL";

// action types for TASK
export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_TASK_REQUEST_SUCCESS = "GET_TASK_REQUEST_SUCCESS";
export const CREATE_TASK_REQUEST = "CREATE_TASK_REQUEST";
export const CREATE_TASK_REQUEST_SUCCESS = "CREATE_TASK_REQUEST_SUCCESS";
export const UPDATE_TASK_REQUEST = "UPDATE_TASK_REQUEST";
export const UPDATE_TASK_REQUEST_SUCCESS = "UPDATE_TASK_REQUEST_SUCCESS";
export const DELETE_TASK_REQUEST = "DELETE_TASK_STARTED";
export const DELETE_TASK_REQUEST_SUCCESS = "DELETE_TASK_REQUEST_SUCCESS";
export const TASK_REQUEST_FAILED = "TASK_REQUEST_FAILED";

// action types for LIST
export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_REQUEST_SUCCESS = "GET_LIST_REQUEST_SUCCESS";
export const CREATE_LIST_REQUEST = "CREATE_LIST_REQUEST";
export const CREATE_LIST_REQUEST_SUCCESS = "CREATE_LIST_REQUEST_SUCCESS";
export const UPDATE_LIST_REQUEST = "UPDATE_LIST_REQUEST";
export const UPDATE_LIST_REQUEST_SUCCESS = "UPDATE_LIST_REQUEST_SUCCESS";
export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const DELETE_LIST_REQUEST_SUCCESS = "DELETE_LIST_REQUEST_SUCCESS";
export const LIST_REQUEST_FAILED = "LIST_REQUEST_FAILED";

// action types for TAG
export const GET_TAG_REQUEST = "GET_TAG_REQUEST";
export const GET_TAG_REQUEST_SUCCESS = "GET_TAG_REQUEST_SUCCESS";
export const CREATE_TAG_REQUEST = "CREATE_TAG_REQUEST";
export const CREATE_TAG_REQUEST_SUCCESS = "CREATE_TAG_REQUEST_SUCCESS";
export const UPDATE_TAG_REQUEST = "UPDATE_TAG_REQUEST";
export const UPDATE_TAG_REQUEST_SUCCESS = "UPDATE_TAG_REQUEST_SUCCESS";
export const DELETE_TAG_REQUEST = "DELETE_TAG_REQUEST";
export const DELETE_TAG_REQUEST_SUCCESS = "DELETE_TAG_REQUEST_SUCCESS";
export const TAG_REQUEST_FAILED = "DELETE_TAG_FAILED";

// action types for ROUTINE

// action types for SCHEDULE
